// Generated by CoffeeScript 1.9.0
(function() {
  var baselib, getSuffix, header, logger, path, rules, utils;

  path = require('path');

  header = require('./header');

  baselib = path.join(module.parent.parent.filename, '../');

  utils = require(path.join(baselib, 'util'));

  logger = utils.logger;

  rules = [header];

  exports.applyRules = function(filePath) {
    var fileName, suffix;
    fileName = path.basename(filePath);
    suffix = getSuffix(fileName);
    if (suffix === 'css') {
      return rules.forEach(function(rule) {
        var ret;
        ret = rule.check(filePath);
        if (ret.length !== 0) {
          return logger.error(filePath + " 检测不通过， 原因：\n" + (ret.join()) + " \n");
        } else {
          return logger.log(filePath + "检查通过 \n");
        }
      });
    }
  };

  getSuffix = function(fileName) {
    var arr, len;
    arr = fileName.split('.');
    len = arr.length;
    if (len === 1) {
      return null;
    }
    return arr[len - 1];
  };

}).call(this);
