// Generated by CoffeeScript 1.9.0
(function() {
  var baselib, header, logger, path, rules, utils;

  path = require('path');

  baselib = path.join(module.parent.parent.filename, '../');

  utils = require(path.join(baselib, 'util'));

  logger = utils.logger;

  header = require('./header');

  rules = [header];

  logger.warning = function() {
    var msg;
    msg = Array.prototype.join.call(arguments, '');
    return console.log('[WRANING] ' + msg);
  };

  exports.applyRules = function(filePath) {
    return rules.forEach(function(rule) {
      var checkResult;
      checkResult = rule.check(filePath);
      if (checkResult.ret === false) {
        if (checkResult.errorMsg) {
          logger.error(filePath + " 检测不通过， 错误信息：\n" + checkResult.errorMsg + " \n");
        }
        if (checkResult.warningMsg) {
          return logger.warning(filePath + " 检测警告， 警告信息：\n" + checkResult.warningMsg + " \n");
        }
      }
    });
  };

}).call(this);
