// Generated by CoffeeScript 1.9.0
(function() {
  var createCssTree, css;

  css = require('css');

  exports.check = function(filePath, content) {
    console.log(css);
    return console.log(css.parse(content).stylesheet.rules);
  };

  createCssTree = function() {};

}).call(this);
