// Generated by CoffeeScript 1.9.0
(function() {
  var alias, findFilePath, fs, importReg, isBeginWithTouch, isCssFile, isLessFile, isSassFile, isSomeTypeFile, listCache, path, requireReg;

  fs = require('fs');

  path = require('path');

  requireReg = /require( ?)\((.*)\)/g;

  importReg = /@import(.*?)[\("'](.*)['"|\)]/g;

  listCache = {};

  alias = {};

  module.exports = function(fekitConfig, folder, callback) {
    var list;
    list = fekitConfig["export"];
    alias = fekitConfig.alias;
    return list.forEach(function(filePath) {
      if (filePath.path) {
        filePath = filePath.path;
      }
      filePath = path.join(process.cwd(), folder, filePath);
      if (isCssFile(filePath)) {
        callback(filePath);
        findFilePath(filePath, callback);
      }
      if (isLessFile(filePath) || isSassFile(filePath)) {
        callback(filePath);
      }
      return listCache[filePath] = 1;
    });
  };

  findFilePath = function(filePath, callback) {
    var content, dirname, findChildList;
    dirname = path.dirname(filePath);
    if (fs.existsSync(filePath)) {
      content = fs.readFileSync(filePath, 'utf-8').toString();
      findChildList = function(reg) {
        var list;
        list = content.match(reg);
        if (list !== null) {
          return list.forEach(function(item) {
            var childFilePath, file, firstFolder, folders;
            file = item.replace(reg, '$2').replace(/["']/g, '');
            folders = file.split('/');
            firstFolder = folders[0];
            if (alias[firstFolder]) {
              folders[0] = alias[firstFolder];
              childFilePath = '';
              folders.forEach(function(f) {
                return childFilePath = path.join(childFilePath, f);
              });
            } else {
              childFilePath = path.resolve(dirname, file);
            }
            if ((isCssFile(filePath) && !isBeginWithTouch(childFilePath)) && listCache[childFilePath] !== 1) {
              callback(childFilePath);
              listCache[childFilePath] = 1;
              return findFilePath(childFilePath, callback);
            }
          });
        }
      };
      findChildList(requireReg);
      return findChildList(importReg);
    }
  };

  isCssFile = function(filePath) {
    return isSomeTypeFile(filePath, '.css');
  };

  isLessFile = function(filePath) {
    return isSomeTypeFile(filePath, '.less');
  };

  isSassFile = function(filePath) {
    return isSomeTypeFile(filePath, '.scss');
  };

  isBeginWithTouch = function(filePath) {
    var basename;
    basename = path.basename(filePath);
    return basename.indexOf('touch-reset') === 0;
  };

  isSomeTypeFile = function(filePath, suffix) {
    var basename, currentSuffix;
    basename = path.basename(filePath);
    currentSuffix = path.extname(basename);
    return currentSuffix === suffix;
  };

}).call(this);
